# Olist E-Commerce Data Analytics Project

## Notebook 2: Data Cleaning

### Objective

The objective of this notebook is to clean all datasets before analysis.

Tasks performed:

- Check missing values
- Check duplicate records
- Verify data types
- Handle inconsistent values
- Create clean datasets for analysis

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_path = r"C:\Users\ASUS\OneDrive\Desktop\E commerce Analytics Project\Data\Raw"

customers = pd.read_csv(f"{data_path}/customers.csv.csv")
geolocation = pd.read_csv(f"{data_path}/geolocation.csv.csv")
order_items = pd.read_csv(f"{data_path}/order_items.csv.csv")
order_payments = pd.read_csv(f"{data_path}/order_payments.csv.csv")
order_reviews = pd.read_csv(f"{data_path}/order_reviews.csv.csv")
orders = pd.read_csv(f"{data_path}/orders.csv.csv")
products = pd.read_csv(f"{data_path}/products.csv.csv")
product_category_name_translation = pd.read_csv(f"{data_path}/product_category_name_translation.csv.csv")
sellers = pd.read_csv(f"{data_path}/sellers.csv.csv")

---------------------------------------------------------------------------------------------------------------------------------

## Checking Missing Values

In [4]:
datasets = {
    "customers":customers,
    "orders":orders,
    "order_items":order_items,
    "order_payments":order_payments,
    "order_reviews":order_reviews,
    "products":products,
    "product_category_name_translation":product_category_name_translation,
    "sellers":sellers,
    "geolocation":geolocation
    
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isnull().sum())

CUSTOMERS
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

ORDERS
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

ORDER_ITEMS
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

ORDER_PAYMENTS
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

ORDER_REVIEWS
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

PRODUCTS
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

PRODUCT_CATEGORY_NAME_TRANSLATION
product_category_name            0
product_category_name_english    0
dtype: int64

SELLERS
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

GEOLOCATION
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [5]:
orders[orders.isnull().any(axis=1)].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00

In [6]:
order_reviews[order_reviews.isnull().any(axis=1)].head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [7]:
products[products.isnull().any(axis=1)].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

## Missing Values Analysis

After checking missing values across all datasets, the following observations were made:

### Orders Dataset

Missing values were found in:

- `order_approved_at`
- `order_delivered_carrier_date`
- `order_delivered_customer_date`

These missing values are expected because some orders are still in statuses such as **processing**, **invoiced**, or **shipped**. Since these orders were not delivered, delivery-related timestamps are naturally unavailable.

**Decision:** No imputation was performed. The missing values were retained.

---

### Order Reviews Dataset

Missing values were found in:

- `review_comment_title`
- `review_comment_message`

Many customers submitted only a review score without writing a text review.

**Decision:** The missing values were retained because they represent the absence of customer comments rather than missing data.

---

### Products Dataset

Missing values were found in:

- `product_category_name`
- `product_name_lenght`
- `product_description_lenght`
- `product_photos_qty`

These missing values are part of the original Olist dataset and represent incomplete product metadata.

Only **2 records** had missing values in `product_weight_g`.

**Decision:**

- Product metadata columns were left unchanged.
- Missing values in `product_weight_g` will be replaced using the median value because it is a numerical column with only two missing records.

In [8]:
products["product_weight_g"] = products["product_weight_g"].fillna(
    products["product_weight_g"].median()
)

In [9]:
products["product_category_name"] = (
    products["product_category_name"]
    .fillna("Unknown Category")
)

In [10]:
products["product_weight_g"].isnull().sum()

0

---------------------------------------------------------------------------------------------------------------------------------

## Duplicate Records Check

The next step is to identify duplicate records in each dataset.

Duplicate records can affect aggregations, KPIs, and analytical results.

Each dataset is checked separately before deciding whether duplicate rows should be removed.

In [11]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()}")

customers: 0
orders: 0
order_items: 0
order_payments: 0
order_reviews: 0
products: 0
product_category_name_translation: 0
sellers: 0
geolocation: 261831

## Duplicate Records Analysis

Duplicate records were checked across all datasets.

Observations:

- No duplicate records were found in Customers, Orders, Order Items, Order Payments, Order Reviews, Products, Sellers, and Product Category Translation.
- The Geolocation dataset contains duplicate records. This is expected in the original Olist dataset because multiple latitude and longitude observations are available for the same ZIP code.

**Decision:**

The duplicate records in the Geolocation dataset were retained because they represent valid geographic observations and are not used in the current business analysis.

---------------------------------------------------------------------------------------------------------------------------------

# Data Type Checking

In [12]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.dtypes)

CUSTOMERS
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

ORDERS
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

ORDER_ITEMS
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

ORDER_PAYMENTS
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

ORDER_REVIEWS
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

PRODUCTS
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

PRODUCT_CATEGORY_NAME_TRANSLATION
product_category_name            object
product_category_name_english    object
dtype: object

SELLERS
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

GEOLOCATION
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

## Data Types Analysis

Most columns have appropriate data types.

However, all date-related columns were imported as **object** data type because CSV files store dates as text.

For accurate date calculations and time-based analysis, these columns will be converted to the `datetime` data type.

In [13]:
date_columns = {
    "orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    
    "order_items": [
        "shipping_limit_date"
    ],
    
    "order_reviews": [
        "review_creation_date",
        "review_answer_timestamp"
    ]
}

In [14]:
for column in date_columns["orders"]:
    orders[column] = pd.to_datetime(orders[column])

for column in date_columns["order_items"]:
    order_items[column] = pd.to_datetime(order_items[column])

for column in date_columns["order_reviews"]:
    order_reviews[column] = pd.to_datetime(order_reviews[column])

In [15]:
print(orders.dtypes)
print(order_items.dtypes)
print(order_reviews.dtypes)

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object
review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

# Cleaning Summary

The following cleaning steps were performed:

- Loaded all nine datasets successfully.
- Checked missing values in every dataset.
- Retained business-related missing values in Orders and Order Reviews.
- Filled missing values in `product_weight_g` using the median.
- Verified duplicate records across all datasets.
- Retained duplicate records in the Geolocation dataset because they represent valid geographic observations.
- Converted all date columns from object to datetime format.

The datasets are now ready for Exploratory Data Analysis (EDA).

In [16]:
products.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"
}, inplace=True)

In [17]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [18]:
clean_path = r"C:\Users\ASUS\OneDrive\Desktop\E commerce Analytics Project\Data\Cleaned"

customers.to_csv(f"{clean_path}/customers_clean.csv", index=False)
orders.to_csv(f"{clean_path}/orders_clean.csv", index=False)
order_items.to_csv(f"{clean_path}/order_items_clean.csv", index=False)
order_payments.to_csv(f"{clean_path}/order_payments_clean.csv", index=False)
order_reviews.to_csv(f"{clean_path}/order_reviews_clean.csv", index=False)
products.to_csv(f"{clean_path}/products_clean.csv", index=False)
product_category_name_translation.to_csv(f"{clean_path}/product_category_name_translation_clean.csv", index=False)
sellers.to_csv(f"{clean_path}/sellers_clean.csv", index=False)
geolocation.to_csv(f"{clean_path}/geolocation_clean.csv", index=False)

print("All cleaned datasets exported successfully.")

All cleaned datasets exported successfully.